include:
  - project: 'wiremind/gitlab-ci-common'
    ref: v10.3.5
    file: 'gitlab-ci-common-libraries.yml'

variables:
  PACKAGE_NAME: chartreuse
  EGG_NAME: chartreuse
  WIREMIND_PYTHON_IMAGE: python:3.6

test-python3.5:
  only:
    - never

linting-python3.5:
  only:
    - never


