include:
  - project: wiremind/devops/gitlab-ci-common
    ref: master
    file: abstract.yml
  - project: wiremind/devops/gitlab-ci-common
    ref: master
    file: libraries/platform.yml

variables:
  PACKAGE_NAME: chartreuse
  EGG_NAME: chartreuse
  DOCKER_BASE_IMAGE: python:3.7

e2e-tests:
  extends: .platform-e2e-test
  variables:
    PACKAGES_TO_INSTALL: "curl git build-base python3-dev libffi-dev libressl-dev musl-dev openssl bash jq py3-pip postgresql-dev"
  
.test:
  # Note: Extends abstract.yml
  variables:
    TEST_DIR: src/$PACKAGE_NAME/tests/unit_tests
