apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-test-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-test-chart.selectorLabels" . | nindent 6 }}
      component: dummy-deployment
  template:
    metadata:
      labels:
        {{- include "my-test-chart.selectorLabels" . | nindent 8 }}
        component: dummy-deployment
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
      terminationGracePeriodSeconds: 1
