apiVersion: "wiremind.io/v1"
kind: ExpectedDeploymentScale
metadata:
  name: {{ include "my-test-chart.fullname" . }}
  labels:
{{ include "my-test-chart.selectorLabels" . | indent 4 }}
spec:
  deploymentName: {{ include "my-test-chart.fullname" . }}
  expectedScale: {{ .Values.replicaCount}}
