apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chartreuse.fullname" . }}
  labels:
    app: {{ template "chartreuse.name" . }}
    chart: {{ template "chartreuse.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  {{- if .Values.allowMigrationFromEmptyDatabase }}
  ALLOW_MIGRATION_FOR_EMPTY_DATABASE: "1"
  {{- else }}
  ALLOW_MIGRATION_FOR_EMPTY_DATABASE: ""
  {{- end }}

