apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chartreuse.fullname" . }}-ephemeral
  labels:
{{ include "chartreuse.labels" . | indent 4 }}
  annotations:
{{ include "chartreuse.annotations.ephemeral" . | indent 4 }}
data:
  # Note: Chartreuse expects false values to be empty string (falsy value) and true values to be non-empty string.
{{- if .Values.alembic.allowMigrationFromEmptyDatabase }}
  CHARTREUSE_ALEMBIC_ALLOW_MIGRATION_FOR_EMPTY_DATABASE: "1"
{{- else }}
  CHARTREUSE_ALEMBIC_ALLOW_MIGRATION_FOR_EMPTY_DATABASE: ""
{{- end }}

{{- if .Values.eslembic.cleanIndex.enabled }}
  CHARTREUSE_ESLEMBIC_ENABLE_CLEAN: "1"
{{- else }}
  CHARTREUSE_ESLEMBIC_ENABLE_CLEAN: ""
{{- end }}

{{- if .Values.eslembic.migrate.enabled }}
  CHARTREUSE_ESLEMBIC_ENABLE_MIGRATE: "1"
{{- else }}
  CHARTREUSE_ESLEMBIC_ENABLE_MIGRATE: ""
{{- end }}

{{- if .Values.stopPods }}
  CHARTREUSE_ENABLE_STOP_PODS: "1"
{{- else }}
  CHARTREUSE_ENABLE_STOP_PODS: ""
{{- end }}

  CHARTREUSE_MIGRATE_CONTAINER_IMAGE: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  CHARTREUSE_MIGRATE_IMAGE_PULL_SECRET: "{{ .Values.image.pullSecret }}"
  CHARTREUSE_RELEASE_NAME: {{ .Release.Name }}
  CHARTREUSE_ALEMBIC_ADDITIONAL_PARAMETERS: "{{ .Values.alembic.additionalParameters }}"

{{- with .Values.additionalEnvironmentVariables }}
{{ toYaml . | indent 2 }}
{{- end }}
