apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chartreuse.fullname" . }}
  labels:
{{ include "chartreuse.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  {{- if .Values.allowMigrationFromEmptyDatabase }}
  ALLOW_MIGRATION_FOR_EMPTY_DATABASE: "1"
  {{- else }}
  ALLOW_MIGRATION_FOR_EMPTY_DATABASE: ""
  {{- end }}
