apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chartreuse.fullname" . }}
  labels:
{{ include "chartreuse.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade,post-rollback
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
data:
  # Chartreuse expects false values to be empty string (falsy value) and true values to be non-empty string.

{{- if .Values.alembic.allowMigrationFromEmptyDatabase }}
  CHARTREUSE_ALEMBIC_ALLOW_MIGRATION_FOR_EMPTY_DATABASE: "1"
{{- else }}
  CHARTREUSE_ALEMBIC_ALLOW_MIGRATION_FOR_EMPTY_DATABASE: ""
{{- end }}

{{- if .Values.eslembic.cleanIndex.enabled }}
  CHARTREUSE_ESLEMBIC_ENABLE_CLEAN: "1"
{{- else }}
  CHARTREUSE_ESLEMBIC_ENABLE_CLEAN: ""
{{- end }}

{{- if .Values.eslembic.upgrade.enabled }}
  CHARTREUSE_ESLEMBIC_ENABLE_UPGRADE: "1"
{{- else }}
  CHARTREUSE_ESLEMBIC_ENABLE_UPGRADE: ""
{{- end }}

{{- if .Values.stopPods }}
  CHARTREUSE_ENABLE_STOP_PODS: "1"
{{- else }}
  CHARTREUSE_ENABLE_STOP_PODS: ""
{{- end }}

  CHARTREUSE_POST_UPGRADE_CONTAINER_IMAGE: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  CHARTREUSE_RELEASE_NAME: {{ .Release.Name }}

  CHARTREUSE_ALEMBIC_ADDITIONAL_PARAMETERS: {{ .Values.alembic.additionalParameters }}
