apiVersion: v1
kind: Secret
metadata:
  name: {{ template "chartreuse.fullname" . }}-ephemeral
  labels:
    app: {{ template "chartreuse.name" . }}
    chart: {{ template "chartreuse.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{ include "chartreuse.annotations.ephemeral" . | indent 4 }}
type: Opaque
stringData:
{{ if .Values.alembic.enabled }}
  CHARTREUSE_ALEMBIC_URL: {{ template "chartreuse.alembic.url" . }}
{{ else }}
  CHARTREUSE_ALEMBIC_URL: ""
{{ end }}
{{ if .Values.eslembic.enabled }}
  CHARTREUSE_ESLEMBIC_URL: {{template "chartreuse.eslembic.url" . }}
{{ else }}
  CHARTREUSE_ESLEMBIC_URL: ""
{{ end }}
{{ with .Values.additionalEnvironmentVariables }}
{{ toYaml . | indent 2 }}
{{ end }}
