apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "chartreuse.serviceAccountName" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
